# Generated by Django 4.0.1 on 2023-04-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_rename_riderequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reqArrvTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Confirmed'), ('P', 'Completed')], default='O', max_length=2),
        ),
    ]
