# Generated by Django 4.0.1 on 2023-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_alter_order_sharerpartysize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sharerPartySize',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
