# Generated by Django 2.2.28 on 2023-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0016_auto_20230426_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sharerPartySize',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
