# Generated by Django 4.0.1 on 2023-04-14 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rider', '0003_alter_order_reqarrvtime_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reqArrvTime',
            new_name='reqArrvDateTime',
        ),
        migrations.AddField(
            model_name='order',
            name='sharerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharerID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='sharerPartySize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=100)),
                ('licensePlateNumber', models.CharField(max_length=10)),
                ('seatCapacity', models.PositiveIntegerField()),
                ('specialVehicleInfo', models.TextField(blank=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rider.driver'),
        ),
    ]
