# Generated by Django 4.0.1 on 2023-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0008_alter_order_sharerpartysize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ownerPartySize',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
